---
#
# @(!--#) @(#) tanium_rb.yaml, sversion 0.1.0, version 004, 11-december-2023
#
- name: Remove Tanium Partition/FS/Mount
  hosts: all
  vars:
    vg_name: rhel
    lv_name: opt_Tanium
    mount_point: /opt/Tanium
  become: yes
  tasks:
    - name: "Get file status on mount point"
      register: stat_output
      stat:
        path: "{{ mount_point }}"

    - name: "Fail if mount point does not exist"
      fail:
        msg: "Mount point {{ mount_point }} does not exist"
      when: stat_output.stat.exists == False

    - name: "Fail if mount point is not a directory"
      fail:
        msg: "Mount point {{ mount_point }} is not a directory"
      when: stat_output.stat.isdir != True

    - name: "Count total number of files and subdirectories in /opt/Tanium"
      register: file_count
      shell:
        cmd: "ls -A1 {{ mount_point }} | wc -l | awk '{ print $1 }'"

    - name: "Report number of files and subdirectories"
      debug:
        var: file_count.stdout[0]

    - name: "Only proceed if total number of files and subdirectories is zero"
      assert:
        that: file_count.stdout[0]|int == 0
        fail_msg: "Cannot remove /opt/Tanium filesystem and logical volume as {{ file_count.stdout[0] }} file(s) exist under /opt/Tanium"

    - name: Unmount the logical volume
      mount:
        path: "{{ mount_point }}"
        state: absent

    - name: "Fail if df command still shows file system as mounted"
      shell:
        cmd: "df -k | grep ' {{ mount_point }}$' ; test $? -eq 1"

    - name: Remove logical volume
      lvol:
        vg: "{{ vg_name }}"
        lv: "{{ lv_name }}"
        state: absent
        force: yes
...
# end of file
